# -*- coding: utf-8 -*-
"""pickle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1US7DKK9Mh2drAU2rNWKCuSRymA3OGLbT
"""

# train_model.py

import pandas as pd
import pickle
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import os

# STEP 1: Load the dataset
df = pd.read_csv("parkinsons.data")

# Drop unnecessary columns
if "name" in df.columns:
    df = df.drop(columns=["name"])

X = df.drop(columns=["status"])
y = df["status"]

# STEP 2: Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# STEP 3: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# STEP 4: Train the model
model = XGBClassifier(use_label_encoder=False, eval_metric="logloss", random_state=42)
model.fit(X_train, y_train)

# STEP 5: Save the model and scaler using pickle
os.makedirs("model", exist_ok=True)

with open("model/xgb_model.pkl", "wb") as f:
    pickle.dump(model, f)

with open("model/scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

print("Model and scaler saved in the 'model/' folder.")